default:
  nestle: "Nestle"
  devon: "Devondale"
  maxig: "Maxigenes"
  anchr: "Anchor"
  
pref:
  dir: "Data/"
  nestle.id: "5480615"
  nestle.col: "#ff6361"
  devon.id: "1805141"
  devon.col: "#bc5090"
  maxig.id: "2087536"
  maxig.col: "#58508d"
  anchr.id: "14817375522"
  anchr.col: "#ffa600"
